# Generated by Django 2.2.6 on 2019-10-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191014_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fetured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
